### ISSUE TITLE
"error: Not enough memory resources are available to process this command" when packaging for Android

### ISSUE THREAD

**Issue by namnq-sipher** [getsentry/sentry-unreal#200] opened 2023-01-30 10:51 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
0.1.1

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unreal?
5.0.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Android

### Steps to Reproduce

1. Enable Upload debug symbols automatically in Sentry project settings.
2. Package the game using UAT command line interface. The full command is: `RunUAT.bat BuildCookRun -nop4 -project='path_to_project_file.uproject' -skipcook -skipstage -skippak -archive -package -archivedirectory='path_to_output_folder' -distribution -clientconfig=Development -cookflavor=ASTC -targetplatform=Android -utf8output -target=MyGameClient`

### Expected Result

The build success and an APK & AAB are outputs.

### Actual Result

The build failed to output an APK file. It failed at the step `uploadSentryNativeSymbolsForRelease`. The error message I got is `error: Not enough memory resources are available to process this command. (os error 8)`

Note 1: if Upload debug symbols automatically in Sentry project settings is disabled, the packaging process will succeed.
Note 2: the task `uploadSentryProguardMappingsRelease` which ran before `uploadSentryNativeSymbolsForRelease` was successful.

I'm using Windows 11 and have 64GB of RAM.

### Any logs or screenshots
![Screenshot 2023-01-30 173422](https://user-images.githubusercontent.com/95368745/215453544-422b3ca6-9224-4d7f-9563-4b3b01219753.jpg)

**Comment by bitsandfoxes** [comment] 2023-02-02 15:54
Sorry to see you running into this issue @namnq-sipher . We'll take a look.

**Comment by namnq-sipher** [comment] 2023-02-09 09:47
thank you @bitsandfoxes

**Comment by namnq-sipher** [comment] 2023-02-11 02:28
Awesome thank you. Is there any update btw.

**Comment by tustanivsky** [comment] 2023-02-13 11:25
> Awesome thank you. Is there any update btw.

We're still trying to identify the origin of this problem. The lack of memory resources doesn't seem to be the case here, so we'll continue looking for a fix. It's possible that the issue is not related to UE package itself but the gradle plugin which is used under the hood for debug symbols upload.

For now I can suggest upgrading to the latest plugin version since it has some important Android-related fixes.

**Comment by tustanivsky** [comment] 2023-02-16 14:40
@namnq-sipher here are two workarounds you can try to fix the problem with Android debug symbols upload:

**1. Increase the JVM heap size**

- Open <EngineInstallDir>\Engine\Build\Android\Java\gradle\gradlew.bat
- Find the line which has `DEFAULT_JVM_OPTS`and set it to something like `set DEFAULT_JVM_OPTS=-Xmx8192M` ( `-Xmx` option here to increase java maximum heap size)

**2. Increase the Page File size on Windows**

- Right-click on Computer and open Properties.
- Select Advanced System Settings
- Click the Advanced tab
- Under Performance, click Settings
- Under Performance Options, click the Advanced tab
- Under the Virtual memory pane, select Change
- Uncheck Automatically manage paging file size for all drives
- Highlight your system drive
- Select Custom size
- Change the Initial size value and the Maximum size value to a higher value
- Click Set and Apply/OK all the way

**Comment by NoCodeBugsFree** [comment] 2023-12-30 10:29
@namnq-sipher , did you resolve the issue? were you at git engine? how huge was your `libUnreal.so` ?
in my case if I use git engine to build android `libUnreal.so` file is relatively huge ( 2-3 gigs for development / shipping for git engine vs 300-400mb for launcher engine) so as I got it correct sentry limit is 2gigs. 
Note , idk how does it work under the hood , but git engine capable of build the game to android without `-distribution` flag 
but the symbols uploads to sentry step is skipped in this case and it allows the entire build finished with success.

**Comment by tustanivsky** [comment] 2024-03-11 13:19
@namnq-sipher as it was mentioned above Sentry has a limit of 2GB for debug symbols files so if that's the case using a custom [Symbol Server](https://docs.sentry.io/platforms/unreal/data-management/debug-files/symbol-servers/) should help to resolve the original issue.

Closing it for now yet feel free to re-open if the problem persists.

**Closed by tustanivsky** 2024-03-11 13:19 UTC
Labels: Bug
