### ISSUE TITLE
When using the Sentry Native Integration, no Crash Dump is written

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#329] opened 2023-07-18 14:51 UTC
### Environment

How do you use Sentry?
Sentry SaaS

Which version of the SDK?
0.8.0

Which version of Unreal?
5.2.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Cooked Windows Client 

### Steps to Reproduce

1. Disable the crash reporter and use the native Sentry integration

### Expected Result
Crash Dump is written locally

### Actual Result
No crash dump is available 

### Any logs or screenshots
N/A

**Comment by tustanivsky** [comment] 2023-07-19 07:20
@Edstub207 You mean that even though the `Enable automatic crash capturing (Windows editor, UE 5.2+)` option is enabled in settings and `CrashReporter` is turned off the crash captured by Sentry has no attachments (dump etc.)?

I've tried to reproduce this on my side with the plugin's sample project on Windows and UE 5.2 however the `.dmp` file gets uploaded to Sentry as expected in both cases when using `CrashReporter` / `sentry-native`. The only thing I've noticed is that dump files have different sizes (3.4 MB for native integration vs 640 Kb for CRC). Not sure if that's important detail though.

**Comment by Edstub207** [comment] 2023-07-19 07:28
@tustanivsky sadly I'm now OOO/AFK for a week, if my memory serves correctly, we couldn't find any crash dumps on the local machine. 

I believe the logs where still truncated, as per the other issue, however, i didn't check the crash dumps on the Sentry website. 

As most crash dumps are written and uploaded as Minidumps there is no way to re parse them to Sentry afaik. So if any point of the Sentry flow fails, for whatever reason, we will not be able to track the crash wtihout it being local on the machine. Maybe it is on the local machine, but it's not in a location I'd normally expect. I didn't see it in the sentry-native folder either. 

I'm also not sure if there are toggles on the Sentry Plugin side to write full dumps or how the dump process works with this new intergration.

**Comment by tustanivsky** [comment] 2023-07-19 07:41
> As most crash dumps are written and uploaded as Minidumps there is no way to re parse them to Sentry afaik. So if any point of the Sentry flow fails, for whatever reason, we will not be able to track the crash wtihout it being local on the machine. Maybe it is on the local machine, but it's not in a location I'd normally expect. I didn't see it in the sentry-native folder either.

When `sentry-native` captures a crash the corresponding dump file can be found in `<BuildDir>/<ProjectName>/.sentry-native/reports`. If it's missing there then most likely native integration wasn't enabled.

> I'm also not sure if there are toggles on the Sentry Plugin side to write full dumps or how the dump process works with this new integration.

No, there is nothing specific for dumps in plugin settings.

**Comment by Edstub207** [comment] 2023-07-27 14:31
@tustanivsky I can confirm that we do have some crash dumps in the above folder as suggested. I've shared the new location with the team and will keep an eye on things. 

Do you expect callstacks to be written in the logs as per the default Unreal implementation or is that no longer a thing?

**Comment by tustanivsky** [comment] 2023-07-28 06:14
> Do you expect callstacks to be written in the logs as per the default Unreal implementation or is that no longer a thing?

We'll look at this in the scope of #336. Apparently, it should be possible to obtain callstacks from the default `FGenericCrashContext` object and if it is so attaching those to the captured event won't be a problem.

**Comment by tustanivsky** [comment] 2023-08-01 12:27
@Edstub207 Just a quick update on writing callstacks to logs when using the native integration for crash capturing - currently there is no way to extract them from the `FGenericCrashContext` object in order to bypass the [aforementioned](https://github.com/getsentry/sentry-unreal/issues/271#issuecomment-1630804458) `sentry-native` limitations. Basically in order to make native integration work we're disabling SEH in Unreal and therefore it doesn't populate callstack info there at all.

Still, you should be able to view a call stack on the issue page if the debug symbols uploading was configured in the Sentry plugin's settings menu.

**Comment by Edstub207** [comment] 2023-08-01 12:36
@tustanivsky Sadly we don't use the built in symbol upload method due to size limitations and also how long it takes. 

For the most part our crashes do resolve, but we do get some that don't for whatever reason, which is what I want to try and avoid. 

Do you see a situation where the callstack being in the logs would be possible?

**Comment by tustanivsky** [comment] 2023-08-02 13:25
> Do you see a situation where the callstack being in the logs would be possible?

If uploading the debug symbols doesn't work for you then continuing using the crash reporter which writes callstacks to the log file might be a better option.

With native integration the only way to get a properly symbolicated callstack is to upload debug symbols to Sentry. `sentry-native` is capable of doing some on-device symbolication (`sentry_options_set_symbolize_stacktraces`) however it can have a performance impact and after some quick testing the results aren't always great in case with Unreal.

Closing this now since the original issue with the missing dump file seems to be resolved. Also, I believe the thing with missing callstacks is a separate issue described in #271.

**Closed by tustanivsky** 2023-08-02 13:25 UTC
Labels: bug, Platform: Unreal
