### ISSUE TITLE
Ensures are incorrectly reported to sentry as "Fatal" errors

### ISSUE THREAD

**Issue by skauker-iw** [getsentry/sentry-unreal#189] opened 2023-01-09 08:35 UTC
### Environment

_How do you use Sentry?_
Sentry SaaS (sentry.io)

_Which version of the SDK?_
0.1.1

_How did you install the package? (Git-URL, Assetstore)_
Git-URL

_Which version of Unreal?_
Unreal 4.26.1

_Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?_
All cases I have tested -- Win64 Editor and packaged Win64 Development configurations (Shipping untested)

### Steps to Reproduce
1. Make sure your project is set up with the crash reporter to report to sentry via the unreal specific endpoint.
2. Open the project (works both in editor or in a packaged game) without a debugger attached
3. Open the debug console, `debug ensure`, which triggers a non-fatal ensure failure. This should trigger the crash reporter to send it to sentry automatically to the configured crash endpoint.

### Expected Result
I would expect a failing ensure to be at most a yellow "warning" or "error" when shown in the UI.

### Actual Result
In the Sentry web UI, ensures are incorrectly marked as "Fatal"
![image](https://user-images.githubusercontent.com/76458238/211264914-6f3e3840-b5a0-4ef1-8d6a-6143cda156bc.png)

I absolutely could be missing something here, or if there was a way to modify the CrashReportClient to allow changing the error level. I'd love to be able to be able to sort out actual crashes vs. failing ensures that correspond to less-critical logic errors.

**Comment by bitsandfoxes** [comment] 2023-01-25 10:39
Hey @skauker-iw, I can confirm that this is still not working as intended. I'll be taking another stab at it in connection to https://github.com/getsentry/sentry/issues/38550#issuecomment-1400241670

**Comment by bitsandfoxes** [comment] 2023-02-13 10:00
As an update: The issue is still reporting the incorrect severity but it is now possible to filter by crashtype itself. `unreal.crash_type:Assert`.

**Comment by donallfg** [comment] 2023-03-30 11:06
Hey, is there any update on this issue? Does the problem lie in symbolicator, crashreporter or sentry itself?

**Comment by bitsandfoxes** [comment] 2023-03-30 19:06
This is a bug or lack of proper support in Sentry itself.

**Comment by donallfg** [comment] 2023-03-30 19:23
Thanks! I don't know if this happened in the last few hours, but I _think_  this might actually be resolved? Looking at our sentry dashboards, our ensures now have a yellow dot next to then, whereas out crashes and checks are marked as unhandled errors!

**Comment by Tobias-Nilsson-Sharkmob** [comment] 2023-05-31 10:02
I can report that this has not resolved itself in its entirety- 
Some ensures are correctly marked as "Warning" in Sentry, but most issues that are ensures are still incorrectly marked as fatal for us. 
The message for the issues does clearly state that it comes from an ensure and the ureal.crash_type does say "Ensure" so we can work around it but it would be nice to have this looked at.

**Comment by bitsandfoxes** [comment] 2023-05-31 14:23
Definitely. It's not forgotten, I do have it on my todo list.

**Closed** 2023-06-15 13:00 UTC
Labels: bug, Platform: Unreal

**Comment by bitsandfoxes** [comment] 2023-06-19 11:01
Took a bit to get that thing out and running. Sorry about that. I tested it locally and it "works on my machine (tm)". Please let me know if you're still running into any issues.

**Comment by skauker-iw** [comment] 2023-06-21 17:45
I can confirm I'm seeing it working beautifully on my panel! Thank you tons!
