### ISSUE TITLE
debug symbols upload - The syntax of the command is incorrect.

### ISSUE THREAD

**Issue by ollyb2001** [getsentry/sentry-unreal#578] opened 2024-06-14 21:31 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

self-hosted

Which version of the SDK?

sentry-unreal-0.17.1-engine5.4-github

How did you install the package? (Git-URL, Assetstore)

Git-URL

Which version of Unreal?

5.4

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?

Editor

### Steps to Reproduce

1: Open Unreal Engine, Compile Successfully

2: Package for Windows on Development

### Expected Result

What you thought would happen.

The project should build and package successfully without any errors.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?
```
UATHelper: Packaging (Windows): Sentry: Start debug symbols upload
UATHelper: Packaging (Windows): The syntax of the command is incorrect.
UATHelper: Packaging (Windows): Error executing C:\Windows\system32\cmd.exe (tool returned code: 255)
UATHelper: Packaging (Windows): [75/75]  Executing post build script (PostBuild-1.bat) (0:01.18 at +1:24)
```

**Comment by tustanivsky** [comment] 2024-06-17 06:00
@ollyb2001 Thank you for raising this - we'll check it out on our end and get back to you.

**Comment by tustanivsky** [comment] 2024-06-24 05:23
@ollyb2001 I wasn't able to reproduce this issue on my side and the symbol upload seems to work as expected in UE 5.4 on Windows. Can you check whether the `sentry.properties` file is present in project's folder root and it contains the credentials required for symbol upload to work (see [docs ](https://docs.sentry.io/platforms/unreal/configuration/debug-symbols/) for more details)? Also, is there any chance that any target platforms/build configurations were disabled in plugin's settings `General -> Misc` section?

**Comment by ollyb2001** [comment] 2024-06-24 06:36
Hi @tustanivsky thanks for getting back to me, I can confirm that sentry.properties is present in the projects folder and that the target platform is selected in the General -> Misc section. Please do note I managed to get it working on my Windows 11 computer but I'm stuck with the same issue on my Windows 10 computer.

**Comment by tustanivsky** [comment] 2024-06-24 12:51
Thank you for those additional details - I'll check it on a Windows 10 PC to see if things could be somehow related to the OS version.

**Comment by tustanivsky** [comment] 2024-06-25 12:01
@ ollyb2001 I've tested this on Windows 10 yet symbol upload also works fine there.

Which Visual Studio version do you have on your Win10 PC? I believe this could be some environment-specific issue however it's hard to tell for sure at this point

**Comment by Pantong51** [comment] 2024-07-24 15:50
I was getting this error for awhile, and on a whim, i checked the file path and made sure there were no spaces. Removing all spaces, fixed the issue. But that is as far as i investigated. I don't have the logs or and screenshots.

this was on win 11, i don't have access to a win 10 pc

**Comment by tustanivsky** [comment] 2024-07-25 07:01
@Pantong51 Which Sentry plugin version do you use? We've fixed a similar problem in `0.18.0` (#561) so it should be working properly

**Comment by Theliraan** [comment] 2024-08-21 17:25
@tustanivsky I have same issue with Sentry 0.19.1 @ Windows 11 Pro 23H2 22631.4037
My auth.token contains symbols: _ + =
Might it be the problem?

**Comment by tustanivsky** [comment] 2024-08-22 06:23
@Theliraan Special characters shouldn't affect symbol upload as the auth token we're using for internal testing contains them too and everything works just as expected.

I'll check if this could be related to locale though, thanks for noticing

**Comment by Theliraan** [comment] 2024-08-22 07:49
> [@Theliraan](https://github.com/Theliraan) Special characters shouldn't affect symbol upload as the auth token we're using for internal testing contains them too and everything works just as expected.
> 
> I'll check if this could be related to locale though, thanks for noticing

Thank you. Also we use custom 0.19.1 on slightly modified version of UE5.3, but it shouldn't be the problem.

**Comment by bruno-garcia** [comment] 2024-10-27 15:07
Did this get resolved? I wonder if we need a way to spit out the command that was used (minus the auth token) to the terminal so we can debug this

**Comment by tustanivsky** [comment] 2024-10-28 18:19
I wasn't able to reproduce this on my end so far. 
We can try echoing paths/params right before executing the Sentry CLI call though and maybe it will give us some fresh insights.

**Comment by Pantong51** [comment] 2024-10-29 21:25
I've not had this issue since the last update

**Comment by tustanivsky** [comment] 2024-10-30 06:31
Alright, I'll close this for now but feel free to re-open in case of running into this issue again.

**Closed by tustanivsky** 2024-10-30 06:31 UTC
Labels: Bug, Waiting for: Product Owner

**Comment by gianluca-manca** [comment] 2025-03-18 14:30
Hi, I encountered the same error.
We are using a custom version of Unreal Engine 4.27.1 and the latest plugin version 0.22.0.
"Sentry: start debug symbol upload"
"< not expected"
Now the workaround that is to set false, in the Sentry plugin project settings, the variable "Upload debug symbol automatically" and then build, and after the successful build, delete the build, reset the value to true, reload the debug symbol using the button and then rebuilding again.
Could you please check this out?

**Comment by tustanivsky** [comment] 2025-03-27 07:27
@gianluca-manca Can you give it another try with version [1.0.0-alpha.4](https://github.com/getsentry/sentry-unreal/releases/tag/1.0.0-alpha.4) of the plugin and see if this issue persist?
