### ISSUE TITLE
Linux: Could not Link HTTP/IPlugin on Build

### ISSUE THREAD

**Issue by Ragora** [getsentry/sentry-unreal#376] opened 2023-09-10 20:23 UTC
### Environment

OS: Ubuntu 23.04

How do you use Sentry: Sentry SaaS
Which version of the SDK: 0.9.0

How did you install the package:
https://github.com/getsentry/sentry-unreal/releases/download/0.9.0/sentry-unreal-0.9.0-engine5.3.zip

Extracted into plugins.

Which version of Unreal: 5.3.0

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows: Editor build.

### Steps to Reproduce

1. Download the archive linked above.
2. Extract into Plugins.
3. Try to build project.

### Expected Result

That build/link would succeed.

### Actual Result

Failed to link HTTP & IPlugin in Unreal.

### Notes

Incidentally it was building fine on the previous plugin version, the one for Unreal 5.2.0 even though I'm on 5.3.0: https://github.com/getsentry/sentry-unreal/releases/download/0.8.0/sentry-unreal-0.8.0-engine5.2.zip

### Any logs or screenshots

Logs:

```
CONSOLE: /home/ragora/Documents/UE5_3/Engine/Build/BatchFiles/Linux/Build.sh  BirthOfLegendsEditor Linux Development -Project="/home/ragora/Documents/Unreal Projects/BirthOfLegends/BirthOfLegends.uproject" -buildscw -clean 
0>Setting up bundled DotNet SDK
0>Running command : dotnet Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll BirthOfLegendsEditor Linux Development -Project=/home/ragora/Documents/Unreal Projects/BirthOfLegends/BirthOfLegends.uproject -buildscw -clean
0>Cleaning BirthOfLegendsEditor binaries...
CONSOLE: /home/ragora/Documents/UE5_3/Engine/Build/BatchFiles/Linux/Build.sh  BirthOfLegendsEditor Linux Development -Project="/home/ragora/Documents/Unreal Projects/BirthOfLegends/BirthOfLegends.uproject" -buildscw 
0>Setting up bundled DotNet SDK
0>Running command : dotnet Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll BirthOfLegendsEditor Linux Development -Project=/home/ragora/Documents/Unreal Projects/BirthOfLegends/BirthOfLegends.uproject -buildscw
0>Log file: /home/ragora/.config/Epic/UnrealBuildTool/Log.txt
0>Using 'git status' to determine working set for adaptive non-unity build (/home/ragora/Documents/Unreal Projects/BirthOfLegends).
0>Creating makefile for BirthOfLegendsEditor (no existing makefile)
0>warning: unused import: `Path`
0> --> build.rs:3:27
0>  |
0>3 | use std::{path::{PathBuf, Path}, env, io::Write};
0>  |                           ^^^^
0>  |
0>  = note: `#[warn(unused_imports)]` on by default
0>
0>warning: `unreal_nyoka` (build script) generated 1 warning
0>warning: unused imports: `Path`, `io::Write`
0> --> src/main.rs:1:27
0>  |
0>1 | use std::{path::{PathBuf, Path}, env, io::Write};
0>  |                           ^^^^        ^^^^^^^^^
0>  |
0>  = note: `#[warn(unused_imports)]` on by default
0>
0>warning: `unreal_nyoka` (bin "main") generated 1 warning (run `cargo fix --bin "main"` to apply 1 suggestion)
0>    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
0>     Running `target/debug/main '/home/ragora/Documents/Unreal Projects/BirthOfLegends/Plugins/CPathFinding_BOL'`
0>Parsing headers for BirthOfLegendsEditor
0>  Running Internal UnrealHeaderTool "/home/ragora/Documents/Unreal Projects/BirthOfLegends/BirthOfLegends.uproject" "/home/ragora/Documents/Unreal Projects/BirthOfLegends/Intermediate/Build/Linux/BirthOfLegendsEditor/Development/BirthOfLegendsEditor.uhtmanifest" -WarningsAsErrors -installed
0>Total of 0 written
0>Reflection code generated for BirthOfLegendsEditor in 2.1785057 seconds
0>------- Build details --------
0>Using toolchain located at '/home/ragora/Documents/UE5_3/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v22_clang-16.0.6-centos7/x86_64-unknown-linux-gnu'.
0>Using clang (/home/ragora/Documents/UE5_3/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v22_clang-16.0.6-centos7/x86_64-unknown-linux-gnu/bin/clang++) version 'clang version 16.0.6 (github.com/llvm/llvm-project 7cbf1a2591520c2491aa35339f227775f4d3adf6)
0>Target: x86_64-unknown-linux-gnu
0>Thread model: posix
0>InstalledDir: /home/ragora/Documents/UE5_3/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v22_clang-16.0.6-centos7/x86_64-unknown-linux-gnu/bin' (string), 16 (major), 0 (minor), 6 (patch)
0>Using bundled libc++ standard C++ library.
0>Using lld linker
0>Using llvm-ar (/home/ragora/Documents/UE5_3/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v22_clang-16.0.6-centos7/x86_64-unknown-linux-gnu/bin/llvm-ar) version 'LLVM (http://llvm.org/):
0>  LLVM version 16.0.6
0>  Optimized build. (string)'
0>Using fast way to relink  circularly dependent libraries (no FixDeps).
0>------------------------------
0>Building BirthOfLegendsEditor...
0>[Upgrade]
0>[Upgrade] Using backward-compatible build settings. The latest version of UE sets the following values by default, which may require code changes:
0>[Upgrade]     bLegacyParentIncludePaths = false               => Omits module parent folders from include paths to reduce compiler command line length. (Previously: true).
0>[Upgrade]     CppStandard = CppStandardVersion.Default        => Updates C++ Standard to C++20 (Previously: CppStandardVersion.Cpp17).
0>[Upgrade]     WindowsPlatform.bStrictConformanceMode = true   => Updates MSVC strict conformance mode to true (Previously: false).
0>[Upgrade] Suppress this message by setting 'DefaultBuildSettings = BuildSettingsVersion.V4;' in BirthOfLegendsEditor.Target.cs, and explicitly overriding settings that differ from the new defaults.
0>[Upgrade]
0>[Upgrade]
0>[Upgrade] Using backward-compatible include order. The latest version of UE has changed the order of includes, which may require code changes. The current setting is:
0>[Upgrade]     IncludeOrderVersion = EngineIncludeOrderVersion.Unreal5_2
0>[Upgrade] Suppress this message by setting 'IncludeOrderVersion = EngineIncludeOrderVersion.Latest;' in BirthOfLegendsEditor.Target.cs.
0>[Upgrade] Alternatively you can set this to 'EngineIncludeOrderVersion.Latest' to always use the latest include order. This will potentially cause compile errors when integrating new versions of the engine.
0>[Upgrade]
0>[Adaptive Build] Excluded from CPathfinding_BOL unity file: unrealffi_types.cpp, Trajectory.cpp, unrealffi.cpp
0>[Adaptive Build] Excluded from Sentry unity file: SentryEvent.cpp, SentryId.cpp, SentryUser.cpp, SentrySettings.cpp, SentryScope.cpp, SentrySubsystem.cpp, SentryBreadcrumb.cpp, SentryScopeDesktop.cpp, SentrySubsystemDesktop.cpp, SentryTransport.cpp, SentryCrashContext.cpp, SentryConvertorsDesktop.cpp, SentrySubsystem.spec.cpp, SentryScope.spec.cpp
0>[Adaptive Build] Excluded from SentryEditor unity file: SentryCliDownloader.cpp, SentrySettingsCustomization.cpp
0>Determining max actions to execute in parallel (12 physical cores, 12 logical cores)
0>  Executing up to 12 processes, one per physical core
0>  Requested 1.5 GB memory per action, 15.29 GB available: limiting max parallel actions to 10
0>------ Building 269 action(s) started ------
0>[1/269] Generate Header [x86-64] VoxelSurfaceNodesImpl.ispc
0>[2/269] Copy [x86-64] VoxelSurfaceNodesImpl.ispc.generated.h
0>[3/269] Generate Header [x86-64] VoxelDetailTextureNodesImpl.ispc
0>[4/269] Copy [x86-64] VoxelDetailTextureNodesImpl.ispc.generated.h
0>[5/269] Generate Header [x86-64] VoxelBufferImpl.ispc
0>[6/269] Copy [x86-64] VoxelBufferImpl.ispc.generated.h
0>[7/269] Generate Header [x86-64] VoxelMathFunctionLibraryImpl.ispc
0>[8/269] Copy [x86-64] VoxelMathFunctionLibraryImpl.ispc.generated.h
0>[9/269] Generate Header [x86-64] VoxelBaseUtilitiesImpl.ispc
0>[10/269] Copy [x86-64] VoxelBaseUtilitiesImpl.ispc.generated.h
0>[11/269] Generate Header [x86-64] VoxelSurfaceFunctionLibraryImpl.ispc
0>[12/269] Copy [x86-64] VoxelSurfaceFunctionLibraryImpl.ispc.generated.h
0>[13/269] Generate Header [x86-64] VoxelHeightSplitterNodeImpl.ispc
0>[14/269] Copy [x86-64] VoxelHeightSplitterNodeImpl.ispc.generated.h
0>[15/269] Generate Header [x86-64] VoxelLerpNodes_Generated.ispc
0>[16/269] Copy [x86-64] VoxelLerpNodes_Generated.ispc.generated.h
0>[17/269] Generate Header [x86-64] VoxelBufferUtilitiesImpl.ispc
0>[18/269] Copy [x86-64] VoxelBufferUtilitiesImpl.ispc.generated.h
0>[19/269] Generate Header [x86-64] VoxelMathConvertNodes_Generated.ispc
0>[20/269] Copy [x86-64] VoxelMathConvertNodes_Generated.ispc.generated.h
0>[21/269] Generate Header [x86-64] VoxelTemplatedMathNodes_Generated.ispc
0>[22/269] Copy [x86-64] VoxelTemplatedMathNodes_Generated.ispc.generated.h
0>[23/269] Generate Header [x86-64] VoxelMathNodes_Generated.ispc
0>[24/269] Copy [x86-64] VoxelMathNodes_Generated.ispc.generated.h
0>[25/269] Generate Header [x86-64] VoxelGenerateSurfacePointsNodeImpl.ispc
0>[26/269] Copy [x86-64] VoxelGenerateSurfacePointsNodeImpl.ispc.generated.h
0>[27/269] Generate Header [x86-64] VoxelCurveNodeImpl.ispc
0>[28/269] Copy [x86-64] VoxelCurveNodeImpl.ispc.generated.h
0>[29/269] Generate Header [x86-64] VoxelRandomNodes_Generated.ispc
0>[30/269] Copy [x86-64] VoxelRandomNodes_Generated.ispc.generated.h
0>[31/269] Generate Header [x86-64] VoxelNoiseNodes_Generated.ispc
0>[32/269] Copy [x86-64] VoxelNoiseNodes_Generated.ispc.generated.h
0>[33/269] Generate Header [x86-64] VoxelBoolNodes_Generated.ispc
0>[34/269] Copy [x86-64] VoxelBoolNodes_Generated.ispc.generated.h
0>[35/269] Generate Header [x86-64] VoxelGradientNodesImpl.ispc
0>[36/269] Copy [x86-64] VoxelGradientNodesImpl.ispc.generated.h
0>[37/269] Generate Header [x86-64] VoxelInterpolationNodes_Generated.ispc
0>[38/269] Copy [x86-64] VoxelInterpolationNodes_Generated.ispc.generated.h
0>[39/269] Generate Header [x86-64] VoxelAdvancedNoiseNodesImpl.ispc
0>[40/269] Copy [x86-64] VoxelAdvancedNoiseNodesImpl.ispc.generated.h
0>[41/269] Generate Header [x86-64] VoxelClampNodes_Generated.ispc
0>[42/269] Copy [x86-64] VoxelClampNodes_Generated.ispc.generated.h
0>[43/269] Compile [x86-64] VoxelMathFunctionLibraryImpl.ispc
0>[44/269] Compile [x86-64] VoxelSurfaceNodesImpl.ispc
0>[45/269] Generate Header [x86-64] VoxelOperatorNodes_Generated.ispc
0>[46/269] Copy [x86-64] VoxelOperatorNodes_Generated.ispc.generated.h
0>[47/269] Compile [x86-64] VoxelBaseUtilitiesImpl.ispc
0>[48/269] Generate Header [x86-64] VoxelVectorNodes_Generated.ispc
0>[49/269] Copy [x86-64] VoxelVectorNodes_Generated.ispc.generated.h
0>[50/269] Compile [x86-64] VoxelBufferImpl.ispc
0>[51/269] Compile [x86-64] VoxelTemplatedMathNodes_Generated.ispc
0>[52/269] Compile [x86-64] VoxelSurfaceFunctionLibraryImpl.ispc
0>[53/269] Compile [x86-64] VoxelLerpNodes_Generated.ispc
0>[54/269] Compile [x86-64] VoxelBufferUtilitiesImpl.ispc
0>[55/269] Compile [x86-64] VoxelOperatorNodes_Generated.ispc
0>[56/269] Compile [x86-64] VoxelBoolNodes_Generated.ispc
0>[57/269] Compile [x86-64] VoxelAdvancedNoiseNodesImpl.ispc
0>[58/269] Compile [x86-64] VoxelClampNodes_Generated.ispc
0>[59/269] Compile [x86-64] VoxelCurveNodeImpl.ispc
0>[60/269] Compile [x86-64] VoxelMathNodes_Generated.ispc
0>[61/269] Compile [x86-64] VoxelGenerateSurfacePointsNodeImpl.ispc
0>[62/269] Compile [x86-64] VoxelVectorNodes_Generated.ispc
0>[63/269] Compile [x86-64] VoxelHeightSplitterNodeImpl.ispc
0>[64/269] Compile [x86-64] VoxelInterpolationNodes_Generated.ispc
0>[65/269] Compile [x86-64] VoxelDetailTextureNodesImpl.ispc
0>[66/269] Compile [x86-64] VoxelGradientNodesImpl.ispc
0>[67/269] Compile [x86-64] VoxelMathConvertNodes_Generated.ispc
0>[68/269] Compile RdAny.cpp
0>[69/269] Compile RName.cpp
0>[70/269] Compile [x86-64] VoxelRandomNodes_Generated.ispc
0>[71/269] Compile SequentialLifetimes.cpp
0>[72/269] Compile color_sinks.cpp
0>[73/269] Compile RdBindableBase.cpp
0>[74/269] Compile [x86-64] VoxelNoiseNodes_Generated.ispc
0>[75/269] Compile PassiveSocket.cpp
0>[76/269] Compile InternRoot.cpp
0>[77/269] Compile SingleThreadScheduler.cpp
0>[78/269] Compile hashing.cpp
0>[79/269] Compile DefaultAbstractDeclaration.cpp
0>[80/269] Compile thirdparty.cpp
0>[81/269] Compile RdExtBase.cpp
0>[82/269] Compile RdReactiveBase.cpp
0>[83/269] Compile Serializers.cpp
0>[84/269] Compile IUnknownInstance.cpp
0>[85/269] Compile ISerializersOwner.cpp
0>[86/269] Compile SynchronousScheduler.cpp
0>[87/269] Compile WireBase.cpp
0>[88/269] Compile MessageBroker.cpp
0>[89/269] Compile countdownlatch.cpp
0>[90/269] Compile DateTime.cpp
0>[91/269] Compile thread_util.cpp
0>[92/269] Compile IRdWireable.cpp
0>[93/269] Compile SimpleSocket.cpp
0>[94/269] Compile PkgInputStream.cpp
0>[95/269] Compile Buffer.cpp
0>[96/269] Compile Protocol.cpp
0>[97/269] Compile ISerializable.cpp
0>[98/269] Compile SignalCookie.cpp
0>[99/269] Compile Lifetime.cpp
0>[100/269] Compile spdlog.cpp
0>[101/269] Compile RdId.cpp
0>[102/269] Compile RdTextBuffer.cpp
0>[103/269] Compile SerializationCtx.cpp
0>[104/269] Compile WireUtil.cpp
0>[105/269] Compile file_sinks.cpp
0>[106/269] Compile SharedPCH.Engine.Cpp17.InclOrderUnreal5_2.h
0>[107/269] Compile fmt.cpp
0>[108/269] Compile Identities.cpp
0>[109/269] Compile InternScheduler.cpp
0>[110/269] Compile SharedPCH.UnrealEd.Cpp17.InclOrderUnreal5_2.h
0>[111/269] Compile LifetimeImpl.cpp
0>[112/269] Compile SocketWire.cpp
0>[113/269] Compile ByteBufferAsyncProcessor.cpp
0>[114/269] Compile PumpScheduler.cpp
0>[115/269] Compile ExtWire.cpp
0>[116/269] Compile stdout_sinks.cpp
0>[117/269] Compile async.cpp
0>[118/269] Compile SingleThreadSchedulerBase.cpp
0>[119/269] Compile Module.VoxelCore.4.cpp
0>[120/269] Compile Module.VoxelCore.2.cpp
0>[121/269] Compile Module.VoxelGraphCore.1.cpp
0>[122/269] Compile Module.VoxelCore.1.cpp
0>[123/269] Compile SharedPCH.UnrealEd.Cpp17.h
0>[124/269] Compile Module.VoxelGraphCore.4.cpp
0>[125/269] Compile Module.VoxelGraphCore.5.cpp
0>[126/269] Compile Module.VoxelGraphCore.2.cpp
0>[127/269] Compile Module.VoxelGraphCore.3.cpp
0>[128/269] Compile ActiveSocket.cpp
0>[129/269] Compile RD.cpp
0>[130/269] Compile SimpleScheduler.cpp
0>[131/269] Compile cfg.cpp
0>[132/269] Compile IProtocol.cpp
0>[133/269] Compile IScheduler.cpp
0>[134/269] Compile LifetimeDefinition.cpp
0>[135/269] Compile Polymorphic.cpp
0>[136/269] Link (lld) libUnrealEditor-RD.so
0>[137/269] Generate Header [x86-64] VoxelHeightmapFunctionLibraryImpl.ispc
0>[138/269] Copy [x86-64] VoxelHeightmapFunctionLibraryImpl.ispc.generated.h
0>[139/269] Compile Module.VoxelGraphNodes.2.cpp
0>[140/269] Compile Module.VoxelGraphNodes.1.cpp
0>[141/269] Generate Header [x86-64] VoxelVoxelizedMeshFunctionLibraryImpl.ispc
0>[142/269] Copy [x86-64] VoxelVoxelizedMeshFunctionLibraryImpl.ispc.generated.h
0>[143/269] Compile Module.VoxelCore.3.cpp
0>[144/269] Link (lld) libUnrealEditor-VoxelCore.so
0>[145/269] Compile Module.VoxelContentEditor.cpp
0>[146/269] Compile Module.RiderLink.cpp
0>[147/269] Link (lld) libUnrealEditor-RiderLink.so
0>[148/269] Compile PCH.BPEx.h
0>[149/269] Compile SentryCrashContext.cpp
0>[150/269] Compile SentryUser.cpp
0>[151/269] Compile Module.VoxelGraphNodes.3.cpp
0>[152/269] Compile Module.VoxelGraphNodes.4.cpp
0>[153/269] Compile SentryBreadcrumb.cpp
0>[154/269] Compile Module.VoxelCoreEditor.cpp
0>[155/269] Compile SentryScopeDesktop.cpp
0>[156/269] Compile Module.VoxelLandmass.cpp
0>[157/269] Compile SentryTransport.cpp
0>[158/269] Compile SentrySubsystemDesktop.cpp
0>[159/269] Compile Module.VoxelGraphCore.7.cpp
0>[160/269] Compile SentrySettings.cpp
0>[161/269] Compile Module.BlockoutToolsPlugin.cpp
0>[162/269] Link (lld) libUnrealEditor-BlockoutToolsPlugin.so
0>[163/269] Compile Module.ShapesVisualizer.cpp
0>[164/269] Link (lld) libUnrealEditor-ShapesVisualizer.so
0>[165/269] Compile SentryScope.cpp
0>[166/269] Compile Module.LowEntryExtendedStandardLibrary.1.cpp
0>[167/269] Compile Module.TribesContactModification.cpp
0>[168/269] Link (lld) libUnrealEditor-TribesContactModification.so
0>[169/269] Compile SentrySubsystem.cpp
0>[170/269] Compile Module.LowEntryExtendedStandardLibrary.4.cpp
0>[171/269] Compile Module.BPEx.cpp
0>[172/269] Link (lld) libUnrealEditor-BPEx.so
0>[173/269] Compile Module.VoxelBlueprint.cpp
0>[174/269] Compile SentryConvertorsDesktop.cpp
0>[175/269] Compile SentrySubsystem.spec.cpp
0>[176/269] Compile SentryId.cpp
0>[177/269] Compile Module.TribesBaseComponents.cpp
0>[178/269] Link (lld) libUnrealEditor-TribesBaseComponents.so
0>[179/269] Compile Module.LowEntryExtendedStandardLibrary.2.cpp
0>[180/269] Compile SentryEvent.cpp
0>[181/269] Compile SentryScope.spec.cpp
0>[182/269] Compile Module.VoxelGraphEditor.1.cpp
0>[183/269] Compile Module.Sentry.cpp
0>[184/269] Link (lld) libUnrealEditor-Sentry.so
0>[185/269] Compile [x86-64] VoxelHeightmapFunctionLibraryImpl.ispc
0>[186/269] Compile MapDataAsset.cpp
0>[187/269] Compile Module.LowEntryExtendedStandardLibrary.3.cpp
0>[188/269] Link (lld) libUnrealEditor-LowEntryExtendedStandardLibrary.so
0>[189/269] Compile Module.CommonLoadingScreen.cpp
0>[190/269] Link (lld) libUnrealEditor-CommonLoadingScreen.so
0>[191/269] Compile Module.VoxelGraphCore.6.cpp
0>[192/269] Compile [x86-64] VoxelVoxelizedMeshFunctionLibraryImpl.ispc
0>[193/269] Compile Module.BlockoutToolsEditorPlugin.cpp
0>[194/269] Compile Module.TribesGameFramework.cpp
0>[195/269] Link (lld) libUnrealEditor-TribesGameFramework.so
0>[196/269] Link (lld) libUnrealEditor-BlockoutToolsEditorPlugin.so
0>[197/269] Compile SentryCliDownloader.cpp
0>[198/269] Compile PCH.BPExKismet.h
0>[199/269] Link (lld) libUnrealEditor-VoxelGraphCore.so
0>[200/269] Link (lld) libUnrealEditor-VoxelCoreEditor.so
0>[201/269] Link (lld) libUnrealEditor-VoxelGraphNodes.so
0>[202/269] Link (lld) libUnrealEditor-VoxelContentEditor.so
0>[203/269] Link (lld) libUnrealEditor-VoxelLandmass.so
0>[204/269] Compile Module.BOLConsole.cpp
0>[205/269] Link (lld) libUnrealEditor-BOLConsole.so
0>[206/269] Compile FactionDataAsset.cpp
0>[207/269] Compile Module.BPExKismet.cpp
0>[208/269] Compile Module.LowEntryExtendedStandardLibraryEditor.cpp
0>[209/269] Link (lld) libUnrealEditor-BPExKismet.so
0>[210/269] Link (lld) libUnrealEditor-LowEntryExtendedStandardLibraryEditor.so
0>[211/269] Compile Module.AdvancedSessions.1.cpp
0>[212/269] Compile SentrySettingsCustomization.cpp
0>[213/269] Compile FactionDataAsset.gen.cpp
0>[214/269] Compile BirthOfLegends.init.gen.cpp
0>[215/269] Compile MapDataAsset.gen.cpp
0>[216/269] Compile Module.BenchmarkSystem.cpp
0>[217/269] Link (lld) libUnrealEditor-BenchmarkSystem.so
0>[218/269] Compile VehicleDataAsset.gen.cpp
0>[219/269] Compile unrealffi.cpp
0>[220/269] Compile Trajectory.cpp
0>[221/269] Compile Module.AdvancedSessions.2.cpp
0>[222/269] Compile Module.EIS.cpp
0>[223/269] Link (lld) libUnrealEditor-EIS.so
0>[224/269] Compile Module.RiderBlueprint.cpp
0>[225/269] Link (lld) libUnrealEditor-RiderBlueprint.so
0>[226/269] Compile unrealffi_types.cpp
0>[227/269] Compile BirthOfLegendsGameModeBase.cpp
0>[228/269] Compile Module.TribesPhysicsComponents.cpp
0>[229/269] Compile Module.SentryEditor.cpp
0>[230/269] Link (lld) libUnrealEditor-SentryEditor.so
0>ld.lld: Error  : undefined symbol: FHttpModule::Get()
0>>>> referenced by SentryCliDownloader.cpp:24 (/home/ragora/Documents/Unreal Projects/BirthOfLegends/Plugins/Sentry/Source/SentryEditor/Private/SentryCliDownloader.cpp:24)
0>>>>               /home/ragora/Documents/Unreal Projects/BirthOfLegends/Plugins/Sentry/Intermediate/Build/Linux/x64/UnrealEditor/Development/SentryEditor/SentryCliDownloader.cpp.o:(FSentryCliDownloader::Download(TFunction<void (bool)> const&))
0>ld.lld: Error  : undefined symbol: IPluginManager::Get()
0>>>> referenced by SentryCliDownloader.cpp:94 (/home/ragora/Documents/Unreal Projects/BirthOfLegends/Plugins/Sentry/Source/SentryEditor/Private/SentryCliDownloader.cpp:94)
0>>>>               /home/ragora/Documents/Unreal Projects/BirthOfLegends/Plugins/Sentry/Intermediate/Build/Linux/x64/UnrealEditor/Development/SentryEditor/SentryCliDownloader.cpp.o:(FSentryCliDownloader::GetSentryCliVersion() const)
0>>>> referenced by SentryCliDownloader.cpp:87 (/home/ragora/Documents/Unreal Projects/BirthOfLegends/Plugins/Sentry/Source/SentryEditor/Private/SentryCliDownloader.cpp:87)
0>>>>               /home/ragora/Documents/Unreal Projects/BirthOfLegends/Plugins/Sentry/Intermediate/Build/Linux/x64/UnrealEditor/Development/SentryEditor/SentryCliDownloader.cpp.o:(FSentryCliDownloader::GetSentryCliPath() const)
0>clang++: Error  : linker command failed with exit code 1 (use -v to see invocation)
0>[231/269] Compile Module.TribesCharacterComponents.cpp
0>[232/269] Link (lld) libUnrealEditor-TribesPhysicsComponents.so
0>[233/269] Link (lld) libUnrealEditor-TribesCharacterComponents.so
0>[234/269] Compile BirthOfLegends.cpp
0>[235/269] Compile Module.VictoryBPLibrary.cpp
0>[236/269] Link (lld) libUnrealEditor-VictoryBPLibrary.so
0>[237/269] Compile VehicleDataAsset.cpp
0>[238/269] Compile BirthOfLegendsGameModeBase.gen.cpp
0>[239/269] Link (lld) libUnrealEditor-BirthOfLegends.so
0>[240/269] Compile Module.TribesModifiers.cpp
0>[241/269] Link (lld) libUnrealEditor-TribesModifiers.so
0>[242/269] Compile Module.VoxelExampleEditor.cpp
0>[243/269] Link (lld) libUnrealEditor-VoxelExampleEditor.so
0>[244/269] Compile Module.CommonStartupLoadingScreen.cpp
0>[245/269] Link (lld) libUnrealEditor-CommonStartupLoadingScreen.so
0>[246/269] Compile Module.CPathfinding_BOL.cpp
0>[247/269] Compile Module.RiderShaderInfo.cpp
0>[248/269] Link (lld) libUnrealEditor-RiderShaderInfo.so
0>[249/269] Compile Module.AdvancedSessions.3.cpp
0>[250/269] Link (lld) libUnrealEditor-CPathfinding_BOL.so
0>[251/269] Link (lld) libUnrealEditor-AdvancedSessions.so
0>[252/269] Compile Module.RiderLC.cpp
0>[253/269] Link (lld) libUnrealEditor-RiderLC.so
0>[254/269] Compile Module.VoxelBlueprintEditor.cpp
0>[255/269] Compile Module.RiderLogging.cpp
0>[256/269] Link (lld) libUnrealEditor-RiderLogging.so
0>[257/269] Compile Module.VoxelLandmassEditor.cpp
0>[258/269] Link (lld) libUnrealEditor-VoxelLandmassEditor.so
0>[259/269] Compile Module.VoxelSpawner.cpp
0>[260/269] Link (lld) libUnrealEditor-VoxelSpawner.so
0>[261/269] Compile Module.RiderGameControl.cpp
0>[262/269] Link (lld) libUnrealEditor-RiderGameControl.so
0>[263/269] Compile Module.VoxelGraphEditor.2.cpp
0>[264/269] Compile Module.VoxelGraphEditor.3.cpp
0>[265/269] Link (lld) libUnrealEditor-VoxelGraphEditor.so
0>[266/269] Link (lld) libUnrealEditor-VoxelBlueprint.so
0>[267/269] Link (lld) libUnrealEditor-VoxelBlueprintEditor.so
0>Total time in Parallel executor: 242.77 seconds
0>Total execution time: 248.39 seconds
```

**Comment by tustanivsky** [comment] 2023-09-11 14:35
@Ragora I've tried to reproduce it on my end however the build was successful. The above issue seems really odd since both `HTTP` and `Projects` modules are linked to `SentryEditor` as they are supposed to be.

Can you share your build settings specified in `ProjectNameEditor.Target.cs`? While playing with it earlier today I've discovered more UE 5.3-related issues (#377) so maybe it's somehow related

**Comment by Ragora** [comment] 2023-09-11 17:44
Of course, and I should do a sanity check build on a blank project while I'm at it to be sure.

**Comment by tustanivsky** [comment] 2023-09-12 07:18
@Ragora I can confirm that it still builds without errors with the above settings both on a plugin sample project and a blank one.

Let's leave this issue open for a while and see if something new comes up.

**Comment by Ragora** [comment] 2023-09-12 16:33
Yup, that works

**Comment by tustanivsky** [comment] 2023-09-25 06:26
Closing it now since the problem seems to be resolved however feel free to reopen if those errors return.

**Closed by tustanivsky** 2023-09-25 06:26 UTC
Labels: bug, Platform: Unreal
