### ISSUE TITLE
Weird event captured: `<unlabeled event>`

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unreal#71] opened 2022-08-20 18:45 UTC
See https://sentry.io/organizations/sentry-sdks/issues/3216058856/?project=6253052

When is it captured? Maybe from the editor?

**Comment by tustanivsky** [comment] 2022-08-21 10:40
> See https://sentry.io/organizations/sentry-sdks/issues/3216058856/?project=6253052
> 
> When is it captured? Maybe from the editor?

I've generated a similar event when running tests in the editor. It's odd though that there is no message attached. I'll take a closer look at this

**Comment by tustanivsky** [comment] 2022-12-28 13:17
The issue was caused by a faulty test which was removed a while ago, closing it now.

**Closed by tustanivsky** 2022-12-28 13:17 UTC
Labels: Platform: Unreal
