### ISSUE TITLE
The automatic source upload fails the packaging process

### ISSUE THREAD

**Issue by dimozaprianov** [getsentry/sentry-unreal#181] opened 2022-12-27 09:36 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK? 0.2.0 at first, then the latest from repo

How did you install the package? Git-URL

Which version of Unreal? 5.0.0

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
In editor while packing

### Steps to Reproduce

Started packaging android build

### Expected Result

Completes successfully

### Actual Result
Senty SDK reports some errors and the build fails.  Most noticeably:

```
error: Not enough memory resources are available to process this command. (os error 8)
> Task :app:uploadSentryNativeSymbolsForRelease FAILED

```
I have 16gb of ram and tried running the packaging process in command line without anything else running. It should have had 8gb+ of free ram

```
warning: proguard mapping 'Z:\AFSProject\app\build\outputs\mapping\release\mapping.txt' was ignored because it does not contain any line information.
> Task :app:uploadSentryProguardMappingsRelease FAILED
error: An organization slug is required (provide with --org)
> compressing mappings
> uploading mappings
                                                                                                                                                                

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.                                                                        
Please attach the full debug log to all bug reports.
```

This one is even weirder because after each packaging there is new data on the sentry settings dashboard. I'm pretty sure I've entered  the correct credentials in the Unreal Sentry settings and there is a correct sentry.properties file in the root of the project

See the logs attached

### Any logs or screenshots
sentry-cli 2.11.0
[package.log](https://github.com/getsentry/sentry-unreal/files/10307265/package.log)

**Comment by tustanivsky** [comment] 2022-12-27 15:01
@dimozaprianov I've checked this on my side and it looks that the game packaging for Android works as expected in UE 5.0. Considering the output log you've shared most likely the debug symbols upload was misconfigured. Can you check whether the `sentry.properties` file is present in your project's root directory and looks similar to this:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/3168564/209684239-0b03017d-06ac-423f-8775-372b7ea23c4d.png">

**Comment by dimozaprianov** [comment] 2022-12-29 06:33
@tustanivsky Yes, it does. It even seems that some parts of the upload is passing through because I got new entries in the proguard section.

**Comment by tustanivsky** [comment] 2022-12-29 12:17
@dimozaprianov On which platform are you facing this issue - Win/Mac/Linux?

**Comment by tustanivsky** [comment] 2022-12-30 09:50
Alright, I've managed to reproduce this on a Windows machine - apparently there is an issue with `upload-debug-symbols-win.ps1`

**Comment by tustanivsky** [comment] 2023-01-02 14:26
@dimozaprianov it turned out that the Sentry gradle plugin used for Android debug symbols upload conflicts with the `Android File Server` plugin enabled by default in Unreal. Please try to disable it in `Settings -> Plugins -> Android -> Android File Server` and give it another shot.

**Comment by dimozaprianov** [comment] 2023-01-03 08:44
@tustanivsky I can confirm the workaround did work for the second part. Unfortunately the 'error: Not enough memory resources are available to process this command. (os error 8)' is still around and the packaging fails.

**Comment by tustanivsky** [comment] 2023-01-05 10:00
> @tustanivsky I can confirm the workaround did work for the second part. Unfortunately the 'error: Not enough memory resources are available to process this command. (os error 8)' is still around and the packaging fails.

@dimozaprianov can you check the Android game packaging with Sentry's debug symbols upload enabled on another PC? I wasn't able to find any relevant info regarding the insufficient resources error nor reproduce it on my side. For now it looks like something machine-specific

**Comment by tustanivsky** [comment] 2023-01-17 06:31
Closing it now, however feel free to reopen if the problem persists

**Closed by tustanivsky** 2023-01-17 06:31 UTC
Labels: bug, Platform: Unreal
